//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Configurator1 {
	using System;
	using System.Collections.Generic;

	public partial class product {
		public int ProductIdentifier { get; set; }
		public string ProductName { get; set; }
		public Nullable<double> BulkDensity { get; set; }
		public Nullable<double> AngleofRepose { get; set; }
		public string Description { get; set; }
		public Nullable<int> TLSPattern { get; set; }
		public Nullable<double> ParPercentageBlending { get; set; }
	}
}
