//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Configurator2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stockpile
    {
        public int StockpileIdentifier { get; set; }
        public string StockpileName { get; set; }
        public Nullable<double> StockpileCapacity { get; set; }
        public int StockpileServiceTypeIdentifier { get; set; }
        public Nullable<double> StockpileStartLimit { get; set; }
        public Nullable<double> StockpileCentreLimit { get; set; }
        public Nullable<double> StockpileEndLimit { get; set; }
        public int PlannedBuildProductIdentifier { get; set; }
        public Nullable<double> BuildAngleOfRepose { get; set; }
        public Nullable<int> StackerNo { get; set; }
        public Nullable<int> ReclaimerQuadrant { get; set; }
        public Nullable<double> StartPositionOffset { get; set; }
        public Nullable<double> StartLuffingAngle { get; set; }
        public Nullable<double> ConeShellStepDistance { get; set; }
        public Nullable<double> BenchHeight { get; set; }
        public Nullable<double> BenchVolume { get; set; }
        public Nullable<double> InitialLuffAngle { get; set; }
        public Nullable<double> InitialLongTravelPosition { get; set; }
        public Nullable<int> StackingRegimeIdentifier { get; set; }
        public Nullable<bool> StackingFormulaIdentifier { get; set; }
        public Nullable<bool> BLStartStackingDirection { get; set; }
        public Nullable<bool> BLStartReclaimingDirection { get; set; }
        public Nullable<double> Bench1LuffAngle { get; set; }
        public Nullable<double> ParBench1SlewAngle { get; set; }
        public Nullable<double> Bench1LongTravelPosition { get; set; }
        public Nullable<double> Bench2LuffAngle { get; set; }
        public Nullable<double> Bench2SlewAngle { get; set; }
        public Nullable<double> Bench2LongTravelPosition { get; set; }
        public Nullable<double> Bench3LuffAngle { get; set; }
        public Nullable<double> Bench3SlewAngle { get; set; }
        public Nullable<double> Bench3LongTravelPosition { get; set; }
        public Nullable<double> StockpileLength { get; set; }
        public Nullable<double> LongTravelStepLength { get; set; }
        public Nullable<double> PilgrimStepLength { get; set; }
        public Nullable<double> InnerSlewLimit { get; set; }
        public Nullable<double> OuterSlewLimit { get; set; }
        public Nullable<double> InnerSlewTurnaroundLimit { get; set; }
        public Nullable<double> OuterSlewTurnaroundLimit { get; set; }
        public Nullable<double> ReclaimRateSetpoint { get; set; }
        public Nullable<double> InitialSlewAngle { get; set; }
        public Nullable<double> InitialSlewInnerTurnaroundLimit { get; set; }
        public Nullable<double> InitialSlewOuterTurnaroundLimit { get; set; }
    }
}
